name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Checkout submodules
      uses: srt32/git-actions@v0.0.3
      with:
        args: git submodule update --init --recursive

    - name: Run install script
      run: ./personal_packages.sh -a

      #    - name: Super-Linter
      #uses: github/super-linter@v2.1.0
